bcc_exe = BCC
bcc_opts = -1- -f- -ms -O1
cppfiles = SERIAL.CPP SETTINGS.CPP UTIL.CPP

build: SDUMP.EXE SLOAD.EXE

test: clean build
	SDUMP.EXE testdata\testdata.txt

SDUMP.EXE:
	$(bcc_exe) $(bcc_opts) -eSDUMP.EXE SDUMP.CPP $(cppfiles)

SLOAD.EXE:
	$(bcc_exe) $(bcc_opts) -eSLOAD.EXE SLOAD.CPP $(cppfiles)

package: build
	mkdir SDUMP
	copy SDUMP.EXE SDUMP\SDUMP.EXE
	copy SDUMP.INI SDUMP\SDUMP.INI
	zip -r SDUMP.ZIP SDUMP

clean:
	del SDUMP.EXE
	del SDUMP.ZIP
	deltree /y SDUMP
